# Generated by Django 3.2.8 on 2022-03-13 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KG',
            fields=[
                ('kg_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_name', models.CharField(max_length=1000)),
                ('kg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kg')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=1000)),
                ('kg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.kg')),
            ],
        ),
    ]
