# Generated by Django 3.2.8 on 2022-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220402_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
