# Generated by Django 3.2.8 on 2022-04-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_kg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kg',
            old_name='kg_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='kg_name',
            new_name='kg',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='kg_name',
            new_name='kg',
        ),
    ]
