# Generated by Django 3.2.8 on 2022-04-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220402_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='relation_name',
            new_name='name',
        ),
    ]
