# Generated by Django 3.2.8 on 2022-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20220403_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kg',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
